### PR TITLE
[WASM] Set the returned type of some Model methods to 'void' type

### LINKED ISSUE #75: [wasm] Return type of some Model methods is not consistent between API doc and implementation
**Test Env:**
Chromium Version : nightly build 65.0.3324.0 (revision f9e1a31)
OS : Mac OS X 10.13.4

**Expected Result:**
The returned type of Model methods is 'void' type

**Actual Result:**
The returned type of Model methods is not 'void' type, it returns 0

**How to reproduce:**
1.Download and install Chromium
2.Launch Chromium
3.Run test case on Chromium: https://brucedai.github.io/nt/test/index-local.html?backend=webgl2
4.Check the result for this test in addOperand API/setOperandValue API/addOperation API/identifyInputsAndOutputs API
for example:

```
    it('check return value is of "void" type', function() {
      return nn.createModel(options).then((model)=>{
        assert.equal(model.addOperand({type: nn.INT32}), undefined);
      });
    });
```
```
    it('check return value is of "void" type', function() {
      return nn.createModel(options).then((model)=>{
        model.addOperand({type: nn.INT32});
        assert.equal(model.setOperandValue(0, new Int32Array([0])), undefined);
      });
    });
```

### PR DESCRIPTION
**Pull request by Wenzhao-Xiang**
passes: 307   failures: 179  duration: 9.67s
=> passes: 311  failures: 175  duration: 7.88s 

Fix #75

### CODE REVIEW

File: src/nn/Model.js [hunk 1]
```diff
@@ -71,7 +71,7 @@ export default class Model {
       value: null
     }
     this._operands.push(operand);
-    return ResultCode.NO_ERROR;
+    //return ResultCode.NO_ERROR;
```
Comment (ibelem) [inline src/nn/Model.js]: Inline comments should be separated by space from the statement. They should start with // and a single space.

https://google.github.io/styleguide/jsguide.html#formatting-comments

It's better to follow coding style.

Comment (Wenzhao-Xiang) [reply src/nn/Model.js]: Done! Thanks for the reference link!

**Comment by ibelem** [comment]
LGTM, thanks!
