### PR TITLE
[WASM] Transpose less than 4D debug

### LINKED ISSUE #1186: [WASM] TRANSPOSE doesn't support non-4D tensor
**Test Env:**
Chromium Version: nightly build  79.0.3917.0(2e4d91c)
Platform: all

**Expected Result:**
Tests should pass 

**Actual Result:**
TRANSPOSE doesn't support non-4D tensor
`
TypeError: Incorrect number of tuple elements for array_int32_4: expected=4, actual=2`

**How to Reproduce:**
Visit:
https://brucedai.github.io/webnnt/test/issue_transpose_2D.html?prefer=fast

### PR DESCRIPTION
**Pull request by akineeic**
Fix #1186.

### CODE REVIEW

**Comment by akineeic** [comment]
I test with wrong backend and didn't notice that perm could be typedArray. Modify the code to adapt that. @huningxin PTAL, thanks!

File: src/nn/wasm/PreparedModel.js [hunk 1]
```diff
@@ -1265,8 +1265,14 @@ export default class PreparedModel {
         OPS_CHECK(output.runtimeshape.DimensionsCount() === perm.length);
 
         // Extend perm to length 4 by appending 0
-        for (let i = perm.length; i < 4; ++i) {
-          perm.push(0);
+        if (perm instanceof Array) {
```
Comment (huningxin) [inline src/nn/wasm/PreparedModel.js:1268]: Is `perm` always a typed array? If it is, please remove this block and just keep the `else` block. Thanks!

Comment (akineeic) [reply src/nn/wasm/PreparedModel.js:1268]: Not always, because according the [code](https://github.com/intel/webml-polyfill/blob/f7edb9685f06fc8ddcb4e48d436690bcc786f580/src/nn/wasm/PreparedModel.js#L1250-L1257) here the default perm is an Array if the operation has only one operand. My first PR is trying to convert typedArray to Array, I almost forgot that.

Comment (huningxin) [reply src/nn/wasm/PreparedModel.js:1268]: Thanks for the clarification. Looks good to me.
